version: '3'

services:

  products:
    build:
      dockerfile: ./products.Dockerfile
    ports:
      - "5000:5000"
    restart: always

  orders:
    build:
      dockerfile: ./orders.Dockerfile
    ports:
      - "6000:6000"
    restart: always

  api_gateway:
    build:
      dockerfile: ./api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      orders:
        condition: service_started
      products:
        condition: service_started
    restart: always